version: '3.8'

services:
  ts-client:
    build:
      context: ./dockerfiles
      dockerfile: client.dockerfile
    image: ts-client
    volumes:
      - ./client:/app
    ports:
      - '3000:3000'